name = ("foley")
address = (".dev.buddymedia.com")
openApp("Firefox")
type("l", KEY_CMD) # switch to address field
type("http://")
paste(name)
wait(1)
paste(address)
type(Key.ENTER)
wait(5)
keyDown(Key.SHIFT+Key.CMD)
type("f")
keyUp(Key.SHIFT+Key.CMD)
type(Key.HOME)