name = input("What is your SSH name (with @ symbol)? EG: foley@ ")
pw = input("what is your password?")
ticket = input("What is the branch you are pulling from? EG:bug-666") 
openApp("terminal")
wait("1319056852637.png")
type("ssh ") 
paste(name)
type ("dev.buddymedia.com")
type (Key.ENTER)
wait(1)
wait("mediac0mspas.png")
paste(pw)
type (Key.ENTER)
wait(1)
type ("cd www")
type (Key.ENTER)
type ("cd Corp-Site")
type (Key.ENTER)
type ("git checkout master")
type (Key.ENTER)
wait(35)
type ("git checkout -b ")
paste(ticket)
type (Key.ENTER)
wait(35)
type ("git pull origin ")
paste(ticket)
type (Key.ENTER)
wait(60)
find("done.png")
openApp("Firefox")
type("l", KEY_CMD) # switch to address field
type ("Http://")
paste(name)
type (Key.BACKSPACE)
type (".dev.buddymedia.com")
type (Key.ENTER)
openApp("Google Chrome")
type("l", KEY_CMD) # switch to address field
type ("Http://")
paste(name)
type (Key.BACKSPACE)
type (".dev.buddymedia.com")
type (Key.ENTER)